export const TODO_ACTION_ADD_DATA = "ADD_DATA";
export const TODO_ACTION_ADD_PAGE = "ADD_PAGE";
export const TODO_ACTION_ADD_SEARCH = "ADD_SEARCH";
export const TODO_ACTION_COMPLETE_CHANGE = "COMPLETE_CHANGE";
export const TODO_ACTION_LOADING_CHANGE = "LOADING_CHANGE";